name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      run-test:
        description: "Run tests?"
        type: boolean
        required: true
      test-type:
        description: "Type of tests to run"
        type: choice
        options:
            - unit
            - integration
            - all
        required: true
      environment:
        description: 'Choose an environment'
        required: true
        type: environment
      build-number:
        description: "Custom build number"
        type: number
        required: false
      message:
        description: "Additional message"
        type: string
        required: false

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Print workflow inputs
              run: |
               echo "Run tests: ${{ inputs.run-tests }}"
               echo "Test type: ${{ inputs.test-type }}"
               echo "Environment: ${{ inputs.environment }}"
               echo "Build number: ${{ inputs.build-number }}"
               echo "Message: ${{ inputs.message }}"

            - name: Run test (if selected)
              if: ${{ inputs.run-test == 'true'}}+
              run: echo "Testing........"
